name: Deploy to AWS S3

on:
  push:
    branches:
      - feature
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: ACTIONS_ALLOW_UNSECURE_COMMANDS
        run: echo 'ACTIONS_ALLOW_UNSECURE_COMMANDS=true' >> $GITHUB_ENV
      - uses: chrislennon/action-aws-cli@v1.1
      - run: 'aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET }}/'
        env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
